################################################################################
# TYPE: Automation
# FILENAME: automation_luz_presenca_corredor.yaml
# NAME: Luzes de Presença do Corredor
################################################################################

#### LIGA LUZ DE PRESENÇA CORREDOR (ESTRELAS)
- alias: 'Luz de Presença Corredor (Estrelas) - Sempre Ligado'
  initial_state: 'on'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 01
  condition:
    condition: and
    conditions:
      - condition: time
        after: '00:00:00'
        before: '23:59:59'
      - condition: state
        entity_id: group.familia
        state: 'home'
      - condition: state
        entity_id: input_boolean.modo_ferias
        state: 'off'
      - condition: state
        entity_id: light.luz_de_presenca_corredor_estrelas
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.luz_de_presenca_corredor_estrelas
    - service: script.notify_zanzito_jorge
      data:
        title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
        message: 'Luzes de Presença do Corredor - LIGADAS'
    - service: script.notify_html5
      data_template:
        title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
        message: 'Luzes de Presença do Corredor - LIGADAS'
        data:
          renotify: '1'
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Luzes de Presença do Corredor - LIGADAS'

####  ####  ####  ####
