################################################################################
# TYPE: Automation
# FILENAME: automation_sistema.yaml
# NAME: Sistema
################################################################################

#### CHECK FOR SYSTEM UPDATES
- alias: 'Update Notifications'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: script.notify_zanzito_jorge
      data:
        title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
        message: 'Nova versão do Home Assistant disponível!'
    - service: script.notify_html5
      data_template:
        title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
        message: 'Nova versão do Home Assistant disponível!'
        data:
          renotify: '1'
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Nova versão do Home Assistant disponível!'

#### NOTIFY SHUTDOWN
- alias: Shutdown
  initial_state: 'on'
  trigger:
    - event: shutdown
      platform: homeassistant
    - event_type: homeassistant.restart
      platform: event
  condition:
    condition: state
    entity_id: input_boolean.modo_ferias
    state: 'on'
  action:
    - service: tts.microsoft_say
      entity_id: media_player.kodi_servidor
      data_template:
        message: 'O Sistema vai reiniciar!'
        cache: false
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - O Sistema vai reiniciar!'

#### NOTIFY STARTUP
- alias: Startup
  initial_state: 'on'
  trigger:
    - event: start
      platform: homeassistant
  condition:
    condition: state
    entity_id: input_boolean.modo_ferias
    state: 'on'
  action:
    - service: tts.microsoft_say
      entity_id: media_player.kodi_servidor
      data_template:
        message: 'O Sistema iniciou'
        cache: false
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - O Sistema iniciou!'
          
#### CHOOSE THEME
- alias: 'Temas'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.hass_template
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{ states.input_select.hass_template.state }}"
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Selecção de Tema'

#### CHOOSE THEME AT SYSTEM STARTUP
- alias: 'Configuração Inicial do Tema'
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: frontend.set_theme
      data:
        name: escuro_azul


####  ####  ####  ####
