################################################################################
# TYPE: Automation
# FILENAME: automation_notificacoes_temp_muito_elevada.yaml
# NAME: Notificação de Temperatura Muito Elevada
################################################################################

#### TEMPERATURA MUITO ELEVADA - Q1 (BIA E CHATY)
- alias: 'Temperaturas muito elevadas Q1'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.temperatura_q1__biachaty
    above: 35.0
  action:
    - service: script.notify_zanzito_todos
      data:
        title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
        message: 'Temperatura no quarto da Bia e Chaty muito elevada (>35ºC)! Erro de medição ou possibilidade de incêndio...'
    - service: script.notify_html5
      data_template:
        title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
        message: 'Temperatura no quarto da Bia e Chaty muito elevada (>35ºC)! Erro de medição ou possibilidade de incêndio...'
        data:
          renotify: '1'
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Temperatura no quarto da Bia e Chaty muito elevada (>35ºC)! Erro de medição ou possibilidade de incêndio...'

#### TEMPERATURA MUITO ELEVADA - Q2 (RAFA)
- alias: 'Temperaturas muito elevadas Q2'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.temperatura_q2__rafa
    above: 35.0
  action:
    - service: script.notify_zanzito_todos
      data:
        title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
        message: 'Temperatura no quarto do Rafa muito elevada (>35ºC)! Erro de medição ou possibilidade de incêndio...'
    - service: script.notify_html5
      data_template:
        title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
        message: 'Temperatura no quarto do Rafa muito elevada (>35ºC)! Erro de medição ou possibilidade de incêndio...'
        data:
          renotify: '1'
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Temperatura no quarto do Rafa muito elevada (>35ºC)! Erro de medição ou possibilidade de incêndio...'

#### TEMPERATURA MUITO ELEVADA - Q3 (PIKE E MIKE)
- alias: 'Temperaturas muito elevadas Q3'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.temperatura_q3__pike_e_mike
    above: 35.0
  action:
    - service: script.notify_zanzito_todos
      data:
        title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
        message: 'Temperatura no quarto do Pike e da Mike muito elevada (>35ºC)! Erro de medição ou possibilidade de incêndio...'
    - service: script.notify_html5
      data_template:
        title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
        message: 'Temperatura no quarto do Pike e da Mike muito elevada (>35ºC)! Erro de medição ou possibilidade de incêndio...'
        data:
          renotify: '1'
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Temperatura no quarto do Pike e da Mike muito elevada (>35ºC)! Erro de medição ou possibilidade de incêndio...'


####  ####  ####  ####
