################################################################################
# TYPE: Configuration
# FILENAME: configuration.yaml
# NAME: Configuração geral do Home Assistant
################################################################################

################################################################################
#### HOME ASSISTANT
################################################################################

homeassistant:
## NAME OF LOCATION
  name: Casa
## LOCATION COORDINATES
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
## ALTITUDE ABOVE SEA LEVEL (IN METERS)
  elevation: 150
## METRIC, IMPERIAL
  unit_system: metric
## C FOR CELCIUS, F FOR FAHRENHEIT
  temperature_unit: C
## TIME_ZONES
  time_zone: Europe/Lisbon
## WHITELIST
  whitelist_external_dirs:
    - /config/cam_snapshots
    - /share/motion
## AUTHORIZATION PROVIDERS
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
    - type: trusted_networks
## CUSTOMIZE
  customize: !include customize.yaml
## PACKAGES
  packages: !include_dir_named packages/

#### FRONTEND
frontend:
  javascript_version: latest
  themes: !include themes.yaml

#### SIDEBAR ITEMS
panel_iframe:
  menu_tasmoadmin:
    title: 'TasmoAdmin'
    url: 'https://192.168.1.200:9541/devices_autoscan'
    icon: mdi:progress-wrench
  menu_nodered:
    title: 'Node-Red'
    url: 'https://192.168.1.200:1880'
    icon: mdi:sitemap
  menu_z2m:
    title: 'Z2M Panel'
    url: 'https://192.168.1.200:1880/ui'
    icon: mdi:zigbee
  menu_log_viewer:
    title: 'Log Viewer'
    url: 'https://192.168.1.200:4277'
    icon: mdi:notebook
  networkmap:
    title: 'Zigbee Map'
    url: '/local/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

#### API
api:

#### CONFIGURATION UI
config:

#### MAP
map:

#### HASS.IO MENU
hassio:

#### HTTP ACCESS
http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
    - 192.168.1.30
    - 192.168.1.200

#### CHECKS FOR AVAILABLE UPDATES
updater:
  include_used_components: true

#### Discover some devices automatically
#discovery:

#### Enables support for tracking state changes over time.
history:
  include:
    domains:
      - sensor
      - light
      - switch

#### LOGGER
logger:
  default: error

#### LOGBOOK
logbook:

#### KU
sun:

#### TEXT TO SPEECH
tts:
  - platform: voicerss
    api_key: !secret tts_voicerss_api_key
    language: 'pt-pt'
    codec: mp3
    format: '16khz_16bit_mono'

#### MQTT
mqtt:
  broker: 192.168.1.200
  port: 1883
  keepalive: 30
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  client_id: ha_ui_client
  discovery: true
  discovery_prefix: homeassistant

#### INFLUXDB
influxdb:
  host: !secret influxdb_host
  port: 8086
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password

#### IPMA @DGOMES
weather:
  - platform: ipma

#### ENERGY METER @DGOMES
electricity:
  utility_edp:
    country: Portugal
    operator: EDP
    plan: Bi-horário - ciclo semanal
    source: sensor.energia_activa_total

#### OCTOPRINT
octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 2

#### GOOGLE CALENDAR
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

#### GOOGLE ASSISTANT
google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - script
    - media_player

#### Z2M NETWORK MAP
zigbee2mqtt_networkmap:


################################################################################
#### SPLIT CONFIGURATION
################################################################################

#### ACTIVE ####

## ALARM - CONTROL PANEL
alarm_control_panel: !include alarm.yaml
## ALARM - CUSTOM PANEL
panel_custom: !include panel_custom.yaml
## CAMERAS
camera: !include cameras.yaml
## DEVICE TRACKER
device_tracker: !include device_tracker.yaml
## DISPLAYS
display: !include displays.yaml
## GROUPS
group: !include groups.yaml
## MEDIA PLAYERS
media_player: !include media_players.yaml
## NOTIFY
notify:  !include notify.yaml
## RECORDER
recorder: !include recorder.yaml
## ZONES
zone: !include zones.yaml

#### INACTIVE ####
## ALERT
#alert:  !include alerts.yaml
## AUTOMATION
#automation: !include_dir_merge_list config_files/automations/
## BINARY SENSORS
#binary_sensor: !include_dir_merge_list config_files/binary_sensors/
## HISTORY GRAPH
#history_graph: !include history_graphs.yaml
## INPUT BOOLEAN
#input_boolean: !include input_booleans.yaml
## INPUT DATE TIME
#input_datetime: !include input_datetime.yaml
## INPUT NUMBER
#input_number: !include input_numbers.yaml
## INPUT SELECT
#input_select: !include input_select.yaml
## INPUT TEXT
#input_text: !include input_text.yaml
## LIGHTS
#light: !include lights.yaml
## REST 
#rest_command: !include rest_commands.yaml
## SCRIPTS
#script: !include_dir_merge_named config_files/scripts/
## SENSORS
#sensor: !include_dir_merge_list config_files/sensors/
## SHELL COMMAND
#shell_command: !include shell_commands.yaml
## SWITCHES
#switch: !include switches.yaml


####  ####  ####  ####
