################################################################################
# TYPE: Sensor
# FILENAME: sensors_templates_presencas.yaml
# NAME: Novas Presenças
################################################################################

#### PRESENÇAS
- platform: template
  sensors:
## JORGE
    jorge_status:
      value_template: '{{ states.input_select.jorge_status_dropdown.state }}'
      friendly_name: 'Jorge'
## LARA
    lara_status:
      value_template: '{{ states.input_select.lara_status_dropdown.state }}'
      friendly_name: 'Lara'
## BIA
    bia_status:
      value_template: '{{ states.input_select.bia_status_dropdown.state }}'
      friendly_name: 'Bia'


####  ####  ####  ####
