################################################################################
# TYPE: Sensor
# FILENAME: sensors_quarto1.yaml
# NAME: Quarto 1
################################################################################

#### SONOFF_TH16_3C3169 (LUZ DE PRESENÇA DO Q1 - BIA/CHATY)
- platform: mqtt
  state_topic: "home/indoor/switch/SONOFF_TH16_3C3169/app"
  name: "Firmware Q1 - Bia/Chaty"
- platform: mqtt
  state_topic: "home/indoor/switch/SONOFF_TH16_3C3169/version"
  name: "Versão Q1 - Bia/Chaty"
- platform: mqtt
  state_topic: "home/indoor/switch/SONOFF_TH16_3C3169/host"
  name: "Hostname Q1 - Bia/Chaty"
- platform: mqtt
  state_topic: "home/indoor/switch/SONOFF_TH16_3C3169/ip"
  name: "IP Q1 - Bia/Chaty"
- platform: mqtt
  state_topic: "home/indoor/switch/SONOFF_TH16_3C3169/mac"
  name: "MAC Q1 - Bia/Chaty"
- platform: mqtt
  state_topic: "home/indoor/switch/SONOFF_TH16_3C3169/temperature"
  name: "Temperatura Q1 - Bia/Chaty"
  unit_of_measurement: °C
  retain: true
  force_update: true
- platform: mqtt
  state_topic: "home/indoor/switch/SONOFF_TH16_3C3169/humidity"
  name: "Humidade Q1 - Bia/Chaty"
  unit_of_measurement: '%'
  retain: true
  force_update: true


####  ####  ####  ####
