################################################################################
# TYPE: Sensor
# FILENAME: sensors_template_presence_beacons.yaml
# NAME: Presence Beacons
################################################################################

#### (B)
- platform: template
  sensors:
    keys_car: 
      value_template: >
        {% if is_state('sensor.keys_car_state', 'unknown') %}
          -100
        {% else %}
          {{ states.sensor.keys_car_state.state | float}}
        {% endif %}

#### (D)
    bt_car_keys:
      friendly_name: 'bt_car_keys'
      value_template: >
        {% if is_state('sensor.keys_car_state', 'unknown') %}
          true
        {% else %}
          false
        {% endif %}


####  ####  ####  ####
