################################################################################
# TYPE: Sensor Template
# FILENAME: sensors_template_meteorologia.yaml
# NAME: Templates de Meteorologia
################################################################################

#### Previsão Meteorologica Matinal
- platform: template
  sensors:
## Previsão Meteorologica Matinal
    morning_meteo:
      friendly_name: 'Previsão Meteorologica Matinal'
      value_template: 'O tempo hoje é {{ states("sensor.pws_weather_1d_metric") }}. Estão {{ states("sensor.pws_temp_c") }} graus em Rio de Mouro.'
## Temperatura Máxima (rua)
    temperatura_maxima_rua:
      friendly_name: 'Temperatura Máxima (rua)'
      icon_template: mdi:arrow-top-right
      value_template: '{{ states.sensor.temperatura_rua_mean.attributes.max_value }}'
      unit_of_measurement: °C
## Temperatura Média (rua)
    temperatura_media_rua:
      friendly_name: 'Temperatura Média (rua)'
      icon_template: mdi:equal
      value_template: '{{ states.sensor.temperatura_rua_mean.state }}'
      unit_of_measurement: °C
## Temperatura Mínima (rua)
    temperatura_minima_rua:
      friendly_name: 'Temperatura Mínima (rua)'
      icon_template: mdi:arrow-bottom-right
      value_template: '{{ states.sensor.temperatura_rua_mean.attributes.min_value }}'
      unit_of_measurement: °C
## Humidade Máxima (rua)
    humidade_maxima_rua:
      friendly_name: 'Humidade Máxima (rua)'
      icon_template: mdi:arrow-top-right
      value_template: '{{ states.sensor.humidade_rua_mean.attributes.max_value }}'
      unit_of_measurement: '%'
## Humidade Média (rua)
    humidade_media_rua:
      friendly_name: 'Humidade Média (rua)'
      icon_template: mdi:equal
      value_template: '{{ states.sensor.humidade_rua_mean.state }}'
      unit_of_measurement: '%'
## Humidade Mínima (rua)
    humidade_minima_rua:
      friendly_name: 'Humidade Mínima (rua)'
      icon_template: mdi:arrow-bottom-right
      value_template: '{{ states.sensor.humidade_rua_mean.attributes.min_value }}'
      unit_of_measurement: '%'
## Pressão Máxima (rua)
    pressao_maxima_rua:
      friendly_name: 'Pressão Máxima (rua)'
      icon_template: mdi:arrow-top-right
      value_template: '{{ states.sensor.pressao_rua_mean.attributes.max_value }}'
      unit_of_measurement: 'mbar'
## Pressão Média (rua)
    pressao_media_rua:
      friendly_name: 'Pressão Média (rua)'
      icon_template: mdi:equal
      value_template: '{{ states.sensor.pressao_rua_mean.state }}'
      unit_of_measurement: 'mbar'
## Pressão Mínima (rua)
    pressao_minima_rua:
      friendly_name: 'Pressão Minima (rua)'
      icon_template: mdi:arrow-bottom-right
      value_template: '{{ states.sensor.pressao_rua_mean.attributes.min_value }}'
      unit_of_measurement: 'mbar'


####  ####  ####  ####
