################################################################################
# TYPE: Sensor
# FILENAME: sensors_thp_min_med_max_casa.yaml
# NAME: Temperatura, Humidade e Pressão de Casa
################################################################################

#### TEMPERATURA MÁXIMA (CASA)
- platform: min_max
  name: 'Temperatura Máxima (casa)'
  type: max
  entity_ids:
    - sensor.temperatura_q1__biachaty
    - sensor.temperatura_q2__rafa
    - sensor.temperatura_q3__pike_e_mike
    - sensor.temperatura_extractor_wc1

#### TEMPERATURA MÍNIMA (CASA)
- platform: min_max
  name: 'Temperatura Mínima (casa)'
  type: min
  entity_ids:
    - sensor.temperatura_q1__biachaty
    - sensor.temperatura_q2__rafa
    - sensor.temperatura_q3__pike_e_mike
    - sensor.temperatura_extractor_wc1

#### TEMPERATURA MÉDIA (CASA)
- platform: min_max
  name: 'Temperatura Média (casa)'
  type: mean
  entity_ids:
    - sensor.temperatura_q1__biachaty
    - sensor.temperatura_q2__rafa
    - sensor.temperatura_q3__pike_e_mike
    - sensor.temperatura_extractor_wc1

#### HUMIDADE MÁXIMA (CASA)
- platform: min_max
  name: 'Humidade Máxima (casa)'
  type: max
  entity_ids:
    - sensor.humidade_q1__biachaty
    - sensor.humidade_q2__rafa
    - sensor.humidade_q3__pike_e_mike
    - sensor.humidade_extractor_wc1

#### HUMIDADE MÍNIMA (CASA)
- platform: min_max
  name: 'Humidade Mínima (casa)'
  type: min
  entity_ids:
    - sensor.humidade_q1__biachaty
    - sensor.humidade_q2__rafa
    - sensor.humidade_q3__pike_e_mike
    - sensor.humidade_extractor_wc1

#### HUMIDADE MÉDIA (CASA)
- platform: min_max
  name: 'Humidade Média (casa)'
  type: mean
  entity_ids:
    - sensor.humidade_q1__biachaty
    - sensor.humidade_q2__rafa
    - sensor.humidade_q3__pike_e_mike
    - sensor.humidade_extractor_wc1


####  ####  ####  ####
