################################################################################
# TYPE: Sensor
# FILENAME: sensors_templates_sun.yaml
# NAME: Templates do Sol
################################################################################

#### SUNSET
- platform: template
  sensors:
    sunset_time:
      icon_template: mdi:weather-sunset-down
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
      friendly_name: 'Pôr do Sol'

#### SUNRISE
- platform: template
  sensors:
    sunrise_time:
      icon_template: mdi:weather-sunset-up
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
      friendly_name: 'Nascer do Sol'

#### DAY/NIGHT
- platform: template
  sensors:
    sun_state:
      value_template: '{% if is_state("sun.sun", "above_horizon") %}Dia{% else %}Noite{% endif %}'
      icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'
      friendly_name: 'Sol'


####  ####  ####  ####
