################################################################################
# TYPE: Sensor
# FILENAME: sensors_wallpanel.yaml
# NAME: Wallpanel
################################################################################

#### ENTRADA
## BATTERY
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/battery"
  name: "Wallpanel Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.value }}'
## BRIGHTNESS
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/brightness"
  name: "Wallpanel Brightness"
  unit_of_measurement: "lx"
  value_template: '{{ value_json.value }}'
## PRESSURE
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/pressure"
  name: "Wallpanel Pressure"
  unit_of_measurement: "mb"
  value_template: '{{ value_json.value }}'


####  ####  ####  ####
