################################################################################
# TYPE: SubGroup
# FILENAME: subgroups_configuracoes.yaml
# NAME: Configurações
################################################################################

#### CONFIGURAÇÕES
grp_main_configs:
  name: Configurações
  icon: mdi:tune-vertical
  control: hidden
  entities:
    - input_boolean.modo_ferias
    - input_boolean.admin_mode
    - input_select.log_level
    - input_boolean.notification_html5
    - input_boolean.notification_telegram
    - input_boolean.notification_zanzito_jorge
    - input_boolean.notification_zanzito_adultos
    - input_boolean.notification_zanzito_todos
    - input_boolean.notification_save_to_file


####    ####    ####    ####