################################################################################
# TYPE: Package
# FILENAME: package_electrical_consumption.yaml
# NAME: Electrical Consumption
################################################################################

#### ESP_Energy_Meter_01
#### OR-WE-501 started counting on 09/09/2017 @ 16h00
#### SDM120C started counting on 20/06/2018 @ 11h30
#### 6,9KVA - Bi-horário, semanal

################################################################################
#### AUTOMATIONS
################################################################################

automation:

#### SAVE DAILY TOTAL
  - alias: 'Grava kWh Diário'
    initial_state: 'on'
    trigger:
      - platform: time
        seconds: '/5'
    condition:
      - condition: template
        value_template: '{{ (as_timestamp( now() ) | timestamp_custom("%Y-%m-%d")) > (as_timestamp(states.sensor.consumo_datahora_diario.state) | timestamp_custom("%Y-%m-%d")) }}'
    action:
      - service: mqtt.publish
        data_template:
          topic: 'home/indoor/sensor/MAID-EM-01/kwh_at_midnight'
          retain: true
          payload_template: '{{ states.sensor.energia_activa_total.state }}'
      - service: mqtt.publish
        data_template:
          topic: 'home/indoor/sensor/MAID-EM-01/kwh_at_midnight_time'
          retain: true
          payload_template: '{{ now() }}'
      - service: script.notify_save_to_file
        data:
          message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - kWh Diários - GRAVADO'

#### SAVE MONTHLY TOTAL
  - alias: 'Grava kWh Mensal'
    initial_state: 'on'
    trigger:
      - platform: time
        seconds: '/5'
    condition:
      - condition: template
        value_template: '{{ (as_timestamp( now() ) | timestamp_custom("%m")) != (as_timestamp(states.sensor.consumo_datahora_mensal.state) | timestamp_custom("%m")) }}'
    action:
      - service: mqtt.publish
        data_template:
          topic: 'home/indoor/sensor/MAID-EM-01/kwh_at_1st_day_month'
          retain: true
          payload_template: '{{ states.sensor.energia_activa_total.state }}'
      - service: mqtt.publish
        data_template:
          topic: 'home/indoor/sensor/MAID-EM-01/kwh_at_1st_day_month_time'
          retain: true
          payload_template: '{{ now() }}'
      - service: script.notify_save_to_file
        data:
          message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - kWh Mensais - GRAVADO'


################################################################################
#### SENSORS
################################################################################

sensor:

#### READINGS
  - platform: mqtt
    name: "Tensão (V)"
    state_topic: "home/indoor/sensor/MAID-EM-01/volt"
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Corrente (A)"
    state_topic: "home/indoor/sensor/MAID-EM-01/amp"
    unit_of_measurement: "A"
  - platform: mqtt
    name: "Potência (W)"
    state_topic: "home/indoor/sensor/MAID-EM-01/watt"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Potência Aparente Activa (VA)"
    state_topic: "home/indoor/sensor/MAID-EM-01/aap"
    unit_of_measurement: "VA"
  - platform: mqtt
    name: "Potência Aparente Reactiva (VAR)"
    state_topic: "home/indoor/sensor/MAID-EM-01/rap"
    unit_of_measurement: "VAR"
  - platform: mqtt
    name: "Factor de Potência (pf)"
    state_topic: "home/indoor/sensor/MAID-EM-01/pf"
    unit_of_measurement: "°"
  - platform: mqtt
    name: "Frequência (Hz)"
    state_topic: "home/indoor/sensor/MAID-EM-01/freq"
    unit_of_measurement: "Hz"
  - platform: mqtt
    name: "Energia Activa Total"
    state_topic: "home/indoor/sensor/MAID-EM-01/tae"
    unit_of_measurement: "KWh"
  - platform: mqtt
    name: "Energia Activa Importada"
    state_topic: "home/indoor/sensor/MAID-EM-01/iae"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Energia Activa Exportada"
    state_topic: "home/indoor/sensor/MAID-EM-01/eae"
    unit_of_measurement: "kWh"

#### TOTALIZERS
  - platform: mqtt
    name: "Consumo dia (kWh)"
    state_topic: "home/indoor/sensor/MAID-EM-01/kwh_at_midnight"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Consumo mês (kWh)"
    state_topic: "home/indoor/sensor/MAID-EM-01/kwh_at_1st_day_month"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Consumo data/hora Diário"
    state_topic: "home/indoor/sensor/MAID-EM-01/kwh_at_midnight_time"
  - platform: mqtt
    name: "Consumo data/hora Mensal"
    state_topic: "home/indoor/sensor/MAID-EM-01/kwh_at_1st_day_month_time"

#### INFLUXDB - VAZIO E FORA VAZIO
  - platform: influxdb
    host: !secret influxdb_host
    username: !secret influxdb_username
    password: !secret influxdb_password
    queries:
      - name: day energy total
        unit_of_measurement: kWh
        where: '"entity_id" = ''potencia_w'' AND time >= ''{{ now().strftime("%Y-%m-%d 00:00:00") }}'' tz(''Europe/Lisbon'')'
        measurement: '"W"'
        group_function: 'integral'
        field: '"value",1h'
        value_template: '{{ (value | float / 1000) | round(1) }}'
      - name: day energy fora vazio
        unit_of_measurement: kWh
        where: '"entity_id" = ''potencia_w'' AND time >= ''{{ now().strftime("%Y-%m-%d 07:00:00")}}'' AND time < ''{{ now().strftime("%Y-%m-%d 23:59:59") }}'' tz(''Europe/Lisbon'')'
        measurement: '"W"'
        group_function: 'integral'
        field: '"value",1h'
        value_template: '{{ (value | float / 1000) | round(1) }}'
      - name: month energy total
        measurement: '(select last(value),entity_id FROM kWh'
        where: '"entity_id" = ''day_energy_vazio'' and time >= ''{{ now().strftime("%Y-%m-01 00:00:00")}}'' group by time(1d) tz(''Europe/Lisbon''))'
        group_function: 'sum'
        field: 'last'
        unit_of_measurement: kWh
        value_template: '{{ (value | float) | round(1) }}'
      - name: month energy vazio
        measurement: '(select last(value),entity_id FROM kWh'
        where: '"entity_id" = ''day_energy_vazio'' and time >= ''{{ now().strftime("%Y-%m-01 00:00:00")}}'' And time < ''{{ now().strftime("%Y-%m-%d 00:00:00") }}''+1d group by time(1d) tz(''Europe/Lisbon''))'
        group_function: 'sum'
        field: 'last'
        unit_of_measurement: kWh
        value_template: '{{ (value | float) | round(1) }}'
      - name: month energy fora vazio
        measurement: '(select last(value),entity_id FROM kWh'
        where: '"entity_id" = ''day_energy_fora_vazio'' and time >= ''{{ now().strftime("%Y-%m-01 00:00:00")}}'' And time < ''{{ now().strftime("%Y-%m-%d 00:00:00") }}''+1d  group by time(1d) tz(''Europe/Lisbon''))'
        group_function: 'sum'
        field: 'last'
        unit_of_measurement: kWh
        value_template: '{{ (value | float) | round(1) }}'


################################################################################
#### SENSOR TEMPLATES
################################################################################

#### ESCALÃO DE POTÊNCIA - 6,9 KVA (30A)

  - platform: template
    sensors:
#### DAILY CONSUMPTION
      consumption_daily_total_kwh:
        friendly_name: 'Total '
        value_template: '{{ ((states.sensor.energia_activa_total.state | float ) - ( states.sensor.consumo_dia_kwh.state | float )) | round(2) }}'
        unit_of_measurement: "kWh"
      consumption_daily_total_euro:
        friendly_name: 'Total '
        value_template: '{{ ((((states.sensor.consumption_daily_total_kwh.state | float) * 0.1997) + (0.3616)) | round (2)) }}'
        unit_of_measurement: "€"

#### MONTHLY CONSUMPTION
      consumption_monthly_total_kwh:
        friendly_name: 'Total '
        value_template: '{{ ((states.sensor.energia_activa_total.state | float ) - ( states.sensor.consumo_mes_kwh.state | float )) | round(2) }}'
        unit_of_measurement: "kWh"
      consumption_monthly_total_euro:
        friendly_name: 'Total '
        value_template: '{{ ((((states.sensor.consumption_monthly_total_kwh.state | float) * 0.1997) + (0.3616)) | round (2)) }}'
        unit_of_measurement: "€"

#### TOTALIZER
      consumption_total_kwh:
        friendly_name: 'Total '
        value_template: '{{ states.sensor.energia_activa_total.state }}'
        unit_of_measurement: "kWh"
      consumption_total_euro:
        friendly_name: 'Total '
        value_template: '{{ (((states.sensor.consumption_total_kwh.state | float) * (0.1997 )) | round(2)) }}'
        unit_of_measurement: "€"

#### INFLUXDB
      day_energy_vazio:
        friendly_name: "Energia Diária Vazio"
        value_template: >-
          {% if (float(states.sensor.day_energy_total.state) - float(states.sensor.day_energy_fora_vazio.state)) | round (3) >=0 %}
          {{ (float(states.sensor.day_energy_total.state) - float(states.sensor.day_energy_fora_vazio.state)) | round (3)}}
          {% else %}
          0
          {% endif %}
        unit_of_measurement: "kWh"
################################################################################
#### GROUPS
################################################################################

group:

#### ENERGY
  energia:
    name: 'Energia'
    entities:
      - sensor.tensao_v
      - sensor.corrente_a
      - sensor.potencia_w
      - sensor.potencia_aparente_activa_va
      - sensor.potencia_aparente_reactiva_var
      - sensor.factor_de_potencia_pf
      - sensor.frequencia_hz
      - sensor.energia_activa_importada
      - sensor.energia_activa_exportada
      - sensor.energia_activa_total

#### DAILY CONSUMPTIONS
  consumos_diarios:
    name: 'Consumos Diários'
    entities:
      - sensor.consumption_daily_total_kwh
      - sensor.consumption_daily_total_euro
      - history_graph.consumos_diarios

#### MONTHLY CONSUMPTIONS
  consumos_mensais:
    name: 'Consumos Mensais'
    entities:
      - sensor.consumption_monthly_total_kwh
      - sensor.consumption_monthly_total_euro
      - history_graph.consumos_mensais

#### TOTALIZERS
  totalizadores:
    name: 'Totalizadores'
    entities:
      - sensor.consumption_total_kwh
      - sensor.consumption_total_euro
      - history_graph.consumos_totais


################################################################################
#### CUSTOMIZE
################################################################################

homeassistant:

  customize:

#### ENERGIA
    sensor.energy_volt:
      icon: mdi:speedometer
    sensor.energy_hertz:
      icon: mdi:speedometer
    sensor.energy_amp:
      icon: mdi:speedometer
      show_last_changed: true
    sensor.energy_watt:
      icon: mdi:speedometer
      show_last_changed: true
    sensor.energy_power_wh:
      icon: mdi:speedometer
      show_last_changed: true
    sensor.energy_apparent_power:
      icon: mdi:speedometer
      show_last_changed: true

#### CONSUMOS DIÁRIOS
    sensor.consumption_daily_total_kwh:
      icon: mdi:sigma
      show_last_changed: true
    sensor.consumption_daily_total_euro:
      icon: mdi:currency-eur
      show_last_changed: true
    sensor.consumption_daily_total_kwh_fora_de_vazio:
      icon: mdi:circle
    sensor.consumption_daily_total_kwh_vazio:
      icon: mdi:circle-outline

#### CONSUMOS MENSAIS
    sensor.consumption_monthly_total_kwh:
      icon: mdi:sigma
      show_last_changed: true
    sensor.consumption_monthly_total_euro:
      icon: mdi:currency-eur
      show_last_changed: true
    sensor.consumption_monthly_total_kwh_fora_de_vazio:
      icon: mdi:circle
    sensor.consumption_monthly_total_kwh_vazio:
      icon: mdi:circle-outline

#### TOTALIZADORES
    sensor.consumption_total_kwh:
      icon: mdi:sigma
      show_last_changed: true
    sensor.consumption_total_euro:
      icon: mdi:currency-eur
      show_last_changed: true
    sensor.consumption_total_fora_de_vazio:
      icon: mdi:circle
    sensor.consumption_total_vazio:
      icon: mdi:circle-outline


####  ####  ####  ####
