################################################################################
# TYPE: Package
# FILENAME: package_.yaml
# NAME: ??
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
#### AUTOMATIONS
################################################################################

#automation:

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER (OLD INPUT_SLIDER)
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

#sensor:

#### 



################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
## SWITCHES
################################################################################

#switch:

#### 


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### GROUPS
################################################################################

#group:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
