################################################################################
# TYPE: Package
# FILENAME: package_last_notifications.yaml
# NAME: Last Notifications
################################################################################


################################################################################
#### SENSORS
################################################################################

sensor:

#### 10
  - platform: command_line
    name: "notificação 10"
    command: "tail -n 10 /config/notifications.txt | sed '2,10d' $1"
#### 09
  - platform: command_line
    name: "notificação 09"
    command: "tail -n 9 /config/notifications.txt | sed '2,9d' $1"
#### 08
  - platform: command_line
    name: "notificação 08"
    command: "tail -n 8 /config/notifications.txt | sed '2,8d' $1"
#### 07
  - platform: command_line
    name: "notificação 7"
    command: "tail -n 07 /config/notifications.txt | sed '2,7d' $1"
#### 06
  - platform: command_line
    name: "notificação 06"
    command: "tail -n 6 /config/notifications.txt | sed '2,6d' $1"
#### 05
  - platform: command_line
    name: "notificação 05"
    command: "tail -n 5 /config/notifications.txt | sed '2,5d' $1"
#### 04
  - platform: command_line
    name: "notificação 04"
    command: "tail -n 4 /config/notifications.txt | sed '2,4d' $1"
#### 03
  - platform: command_line
    name: "notificação 03"
    command: "tail -n 3 /config/notifications.txt | sed '2,3d' $1"
#### 02
  - platform: command_line
    name: "notificação 02"
    command: "tail -n 2 /config/notifications.txt | sed '2,2d' $1"
#### 01
  - platform: command_line
    name: "notificação 01"
    command: "tail -n 1 /config/notifications.txt | sed '2,1d' $1"


################################################################################
#### GROUPS
################################################################################

group:

#### NOTIFICATION LIST
  grp_last_notifications:
    name: Últimas Notificações
    control: hidden
    entities:
      - sensor.notificacao_01
      - sensor.notificacao_02
      - sensor.notificacao_03
      - sensor.notificacao_04
      - sensor.notificacao_05
      - sensor.notificacao_06
      - sensor.notificacao_07
      - sensor.notificacao_08
      - sensor.notificacao_09
      - sensor.notificacao_10


################################################################################
#### CUSTOMIZE
################################################################################

homeassistant:

  customize:

#### LISTA DE NOTIFICAÇÕES
    sensor.notificacao_01:
      icon: mdi:bell-ring
      friendly_name: '01'
    sensor.notificacao_02:
      icon: mdi:bell
      friendly_name: '02'
    sensor.notificacao_03:
      icon: mdi:bell
      friendly_name: '03'
    sensor.notificacao_04:
      icon: mdi:bell
      friendly_name: '04'
    sensor.notificacao_05:
      icon: mdi:bell
      friendly_name: '05'
    sensor.notificacao_06:
      icon: mdi:bell
      friendly_name: '06'
    sensor.notificacao_07:
      icon: mdi:bell
      friendly_name: '07'
    sensor.notificacao_08:
      icon: mdi:bell
      friendly_name: '08'
    sensor.notificacao_09:
      icon: mdi:bell
      friendly_name: '09'
    sensor.notificacao_10:
      icon: mdi:bell
      friendly_name: '10'


####  ####  ####  ####
