################################################################################
# TYPE: Package
# FILENAME: package_.yaml
# NAME: Google Geocode Tracking
################################################################################

#### https://github.com/michaelmcarthur/GoogleGeocode-HASS

#### https://maps.googleapis.com/maps/api/geocode/json?latlng=38.782591,-9.322595&key=AIzaSyAhoRZu3gqGpzS2znC3wW2LBM9dRUUbZCE&language=pt

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
#### AUTOMATIONS
################################################################################

#automation:

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### Geocode Jorge  
  - platform: google_geocode
    name: jorge_geocode
    origin: device_tracker.jmra
    options: street_number, street, city
    display_zone: hide
    api_key: !secret google_geocode_api_key

  - platform: google_geocode
    name: jorge_geocode_full
    origin: device_tracker.jmra
    options: formatted_address
    display_zone: hide
    api_key: !secret google_geocode_api_key

#### Geocode Lara  
  - platform: google_geocode
    name: lara_geocode
    origin: device_tracker.lslma
    options: street_number, street, city
    display_zone: hide
    api_key: !secret google_geocode_api_key

  - platform: google_geocode
    name: lara_geocode_full
    origin: device_tracker.lslma
    options: formatted_address
    display_zone: hide
    api_key: !secret google_geocode_api_key

#### Geocode Bia  
  - platform: google_geocode
    name: bia_geocode
    origin: device_tracker.bama
    options: street_number, street, city
    display_zone: hide
    api_key: !secret google_geocode_api_key

  - platform: google_geocode
    name: bia_geocode_full
    origin: device_tracker.bama
    options: formatted_address
    display_zone: hide
    api_key: !secret google_geocode_api_key


################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### GROUPS
################################################################################

#group:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

homeassistant:

  customize:

#### 
    sensor.jorge_geocode:
      friendly_name: 'Jorge'
    sensor.jorge_geocode_full:
      friendly_name: 'Morada Jorge'
    sensor.lara_geocode:
      friendly_name: 'Lara'
    sensor.lara_geocode_full:
      friendly_name: 'Morada Lara'
    sensor.bia_geocode:
      friendly_name: 'Bia'
    sensor.bia_geocode_full:
      friendly_name: 'Morada Bia'


####  ####  ####  ####
