################################################################################
# TYPE: Package
# FILENAME: package_.yaml
# NAME: ??
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
#### AUTOMATIONS
################################################################################

#automation:

#### 
#  - alias: 'Water Sensor - Backyard'
#    initial_state: True
#    trigger:
#      platform: mqtt
#      topic: home/433toMQTT
#      payload: 88888888
#    action:
#      - service: automation.turn_off
#        entity_id: automation.water_sensor__backyard
#      - service: notify.notify
#        data_template:
#          title: ""
#          message: "It is raining now"
#      - delay:
#          seconds: 10
#      - service: automation.turn_on
#        entity_id: automation.water_sensor__backyard


################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER (OLD INPUT_SLIDER)
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### HALL DE ENTRADA - MOTION
  - platform: mqtt
    name: "Hall de Entrada - State"
    state_topic: "home/indoor/switch/SONOFF-RF-BRIDGE-C72AEA/rfin"
    availability_topic: "home/indoor/switch/SONOFF-RF-BRIDGE-C72AEA/status"
    qos: 1
    payload_on: "30D401A404C4D3AA5E"
    payload_available: 1
    payload_not_available: 0
    optimistic: false
    retain: true

#### HALL DE ENTRADA - TAMPER
  - platform: mqtt
    name: "Hall de Entrada - Tamper"
    state_topic: "home/indoor/switch/SONOFF-RF-BRIDGE-C72AEA/rfin"
    availability_topic: "home/indoor/switch/SONOFF-RF-BRIDGE-C72AEA/status"
    qos: 1
    payload_on: "311001A404BAD3AA5E"
    payload_available: 1
    payload_not_available: 0
    optimistic: false
    retain: true

#### CORREDOR - MOTION
#  - platform: mqtt
#    name: "Corredor - Motion"
#    state_topic: "home/indoor/switch/SONOFF-RF-BRIDGE-C72AEA/rfin"
#    availability_topic: "home/indoor/switch/SONOFF-RF-BRIDGE-C72AEA/status"
#    qos: 1
#    payload_on: "30D401A404C4D3AA5E"
#    payload_available: 1
#    payload_not_available: 0
#    optimistic: false
#    retain: true

#### CORREDOR - MOTION
#  - platform: mqtt
#    name: "Corredor - Tamper"
#    state_topic: "home/indoor/switch/SONOFF-RF-BRIDGE-C72AEA/rfin"
#    availability_topic: "home/indoor/switch/SONOFF-RF-BRIDGE-C72AEA/status"
#    qos: 1
#    payload_on: "311001A404BAD3AA5E"
#    payload_available: 1
#    payload_not_available: 0
#    optimistic: false
#    retain: true

################################################################################
#### SENSOR TEMPLATES
################################################################################

#  - platform: template
#    sensors:

#### HALL DE ENTRADA - STATE
 #     motion_hall_de_entrada:
 #       friendly_name: 'Hall de Entrada'
 #       value_template: >-
 #         {% if is_state('~{{ states.sensor.hall_de_entrada__motion.state }}', '30D401A404C4D3AA5E') %}
 #           Movimento
 #         {% else %}
 #           OK
 #         {% endif %}

#### CORREDOR - STATE
#      motion_hall_de_entrada:
#        friendly_name: 'Hall de Entrada'
#        value_template: >-
#          {% if is_state('sensor.hall_de_entrada__motion', '30D401A404C4D3AA5E') %}
#            Movimento
#          {% else %}
#            OK
#          {% endif %}

################################################################################
## BINARY SENSORS
################################################################################

binary_sensor:

#### 
  - platform: mqtt
    name: "Hall de Entrada - Motion"
    state_topic: "home/indoor/switch/SONOFF-RF-BRIDGE-C72AEA/rfin"
    payload_off: "0"
    payload_on: "311A01A404C4D3AA5E"
    qos: 0
    device_class: motion


################################################################################
## BINARY SENSORS TEMPLATE
################################################################################

  - platform: template
    sensors:

#### HALL DE ENTRADA - STATE
      motion_hall_de_entrada:
        friendly_name: 'Hall de Entrada'
        value_template: >-
          {% if is_state('~{{ states.sensor.hall_de_entrada__motion.state }}', '311A01A404C4D3AA5E') %}
            Movimento
          {% else %}
            OK
          {% endif %}

################################################################################
## SWITCHES
################################################################################

#switch:

#### 


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### GROUPS
################################################################################

group:

#### HALL DE ENTRADA MOTION
  grp_motion_sensors:
    name: Sensores de Movimento
    icon: mdi:walk
    entities:
      - binary_sensor.motion_hall_de_entrada


################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
