################################################################################
# TYPE: Package
# FILENAME: package_.yaml
# NAME: Hidden Cameras
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
#### AUTOMATIONS
################################################################################

automation:

#### Show All Cameras
  - alias: Show All Cameras
    trigger:
      platform: state
      entity_id: input_boolean.admin_mode
      to: 'on'
    action:
      service: group.set_visibility
      entity_id: group.hidden_cameras
      data:
        visible: True

#### Hide All Cameras
  - alias: Hide All Cameras
    trigger:
      platform: state
      entity_id: input_boolean.admin_mode
      to: 'off'
    action:
      service: group.set_visibility
      entity_id: group.hidden_cameras
      data:
        visible: False


################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

input_boolean:

#### ADMINISTRATOR MODE
   admin_mode:
     name: Admin Mode
     initial: off
     icon: mdi:account-key 


################################################################################
#### INPUT NUMBER
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

#sensor:

#### 



################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### GROUPS
################################################################################

group:

#### CAMERAS
  cameras:
    name: Cameras
    entities:
      - camera.homecam01_porta_rua
      - camera.quarto_3
    
#### HIDDEN CAMERAS
  hidden_cameras:
    name: Hidden Cameras
    entities:
      - camera.kiosk_entrada


################################################################################
#### CUSTOMIZE
################################################################################

homeassistant:

  customize:

#### 
    input_boolean.admin_mode:
      persistent: true
      confirm_controls_show_lock: true


####  ####  ####  ####
