################################################################################
# TYPE: Package
# FILENAME: package_device_trackers.yaml
# NAME: Localização da Familia
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

script:

#### JMRA Home
  set_jmra_home:
    alias: Força em Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/jmra/location'
          retain: true
          payload: !secret payload_home

#### JMRA Not Home
  set_jmra_not_home:
    alias: Força Fora de Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/jmra/location'
          retain: true
          payload: '{"latitude": 0.0,"longitude": 0.0}'

#### LSLMA Home
  set_lslma_home:
    alias: Força em Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/lslma/location'
          retain: true
          payload: !secret payload_home

#### LSLMA Not Home
  set_lslma_not_home:
    alias: Força Fora de Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/lslma/location'
          retain: true
          payload: '{"latitude": 0.0,"longitude": 0.0}'

#### BAMA Home
  set_bama_home:
    alias: Força em Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/bama/location'
          retain: true
          payload: !secret payload_home

#### BAMA Not Home
  set_bama_not_home:
    alias: Força Fora de Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/bama/location'
          retain: true
          payload: '{"latitude": 0.0,"longitude": 0.0}'


################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
#### AUTOMATIONS
################################################################################

#automation:

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### BATERIA

## PIKE
  - platform: mqtt
    state_topic: "zanzito/jmra/battery_level"
    name: "Pike - Bateria"
    unit_of_measurement: '%'
    retain: true

## MIKE
  - platform: mqtt
    state_topic: "zanzito/lslma/battery_level"
    name: "Mike - Bateria"
    unit_of_measurement: '%'
    retain: true

## BIA
  - platform: mqtt
    state_topic: "zanzito/bama/battery_level"
    name: "Bia - Bateria"
    unit_of_measurement: '%'
    retain: true 

#### LOCALIZAÇÃO

## JORGE
  - platform: mqtt
    state_topic: "zanzito/jmra/location"
    name: "jmra gps"
    retain: true

## LARA
  - platform: mqtt
    state_topic: "zanzito/lslma/location"
    name: "lslma gps"
    retain: true

## BIA
  - platform: mqtt
    state_topic: "zanzito/bama/location"
    name: "bama gps"
    retain: true


################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
## SWITCHES
################################################################################

#switch:

#### 


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### GROUPS
################################################################################

group:

#### JORGE
  jorge_jmra:
    name: Jorge Assunção
    entities:
      - device_tracker.jmra
      - sensor.pike__bateria
      - script.set_jmra_home
      - script.set_jmra_not_home
      - camera.jorge

#### LARA
  lara_lslma:
    name: Lara Assunção
    entities:
      - device_tracker.lslma
      - sensor.mike__bateria
      - script.set_lslma_home
      - script.set_lslma_not_home
      - camera.lara

#### BIA
  bia_bama:
    name: Beatriz Assunção
    entities:
      - device_tracker.bama
      - sensor.bia__bateria
      - script.set_bama_home
      - script.set_bama_not_home
      - camera.bia 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
