################################################################################
# TYPE: Package
# FILENAME: package_.yaml
# NAME: ??
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
#### AUTOMATIONS
################################################################################

#automation:

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER (OLD INPUT_SLIDER)
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

#sensor:

#### 



################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

binary_sensor:

#### GET DEVICE STATE
  - platform: mqtt
    name: "dumb2smart"
    state_topic: "home/test/status"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity


################################################################################
## SWITCHES
################################################################################

#switch:

#### 



################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### GROUPS
################################################################################

#group:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
