################################################################################
# TYPE: Package
# FILENAME: package_.yaml
# NAME: ??
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

script:
 
#### LUZES DE PRESENÇA DOS QUARTOS
  auto_lp_quartos_on:
    alias: Ligar
    sequence:
      - service: automation.trigger
        entity_id: automation.lp_quartos__auto_on
  
  auto_lp_quartos_off:
    alias: Desligar
    sequence:
      - service: automation.trigger
        entity_id: automation.lp_quartos__auto_off


################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
#### AUTOMATIONS
################################################################################

automation:

#### LIGA LUZES DE PRESENÇA DOS QUARTOS
  - alias: 'LP Quartos - Auto ON'
    initial_state: True
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ states.sensor.auto_lp_quartos_light_start_seconds.state | int <= ((((((as_timestamp (now())) | timestamp_custom("%H")) | int) * 3600) + ((((as_timestamp (now())) | timestamp_custom("%M")) | int) * 60) + (((as_timestamp (now())) | timestamp_custom("%S")) | int))) }}'
        - condition: state
          entity_id: group.familia
          state: 'home'
        - condition: state
          entity_id: input_boolean.modo_ferias
          state: 'off'
        - condition: state
          entity_id: 'group.lp_quartos'
          state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id: group.lp_quartos
      - service: script.notify_zanzito_jorge
        data:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes de Presença dos Quartos - LIGADAS'
      - service: script.notify_html5
        data_template:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes de Presença dos Quartos - LIGADAS'
          data:
            renotify: '1'
      - service: script.notify_save_to_file
        data:
          message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Luzes de Presença dos Quartos - LIGADAS'
  
#### DESLIGA LUZES DE PRESENÇA DOS QUARTOS
  - alias: 'LP Quartos - Auto OFF'
    initial_state: True
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ states.sensor.auto_lp_quartos_light_stop_seconds.state | int <= ((((((as_timestamp (now())) | timestamp_custom("%H")) | int) * 3600) + ((((as_timestamp (now())) | timestamp_custom("%M")) | int) * 60) + (((as_timestamp (now())) | timestamp_custom("%S")) | int))) <= states.sensor.auto_lp_quartos_light_start_seconds.state | int }}'
        - condition: state
          entity_id: 'group.lp_quartos'
          state: 'on'
    action:
      - service: light.turn_off
        entity_id: group.lp_quartos
      - service: script.notify_zanzito_jorge
        data:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes de Presença dos Quartos - DESLIGADAS'
      - service: script.notify_html5
        data_template:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes de Presença dos Quartos - DESLIGADAS'
          data:
            renotify: '1'
      - service: script.notify_save_to_file
        data:
          message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Luzes de Presença dos Quartos - DESLIGADAS' 

################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER
################################################################################

input_number:

#### Temporizador das luzes de presença dos quartos
  auto_lp_quartos_light_offset_on:
    name: Minutos Acerto ( - | + )
    icon: mdi:timer
    min: -90
    max: 90
    step: 10

  auto_lp_quartos_light_offset_off:
    name: Minutos Acerto ( - | + )
    icon: mdi:timer
    min: -90
    max: 90
    step: 10 

################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### 



################################################################################
#### SENSOR TEMPLATES
################################################################################

#### LUZES DE PRESENÇA DOS QUARTOS
  - platform: template
    sensors:
      auto_lp_quartos_light_group_state:
        friendly_name: 'Estado actual '
        icon_template: mdi:apple-keyboard-option
        value_template: '{{ states.group.lp_quartos.state }}'
      auto_lp_quartos_light_start:
        friendly_name: 'Luzes acendem às '
        icon_template: mdi:lightbulb-on-outline
        value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) + (states("input_number.auto_lp_quartos_light_offset_on") | int) * 60) | timestamp_custom("%H:%M") }}'
      auto_lp_quartos_light_stop:
        friendly_name: 'Luzes apagam às '
        icon_template: mdi:lightbulb-outline
        value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_rising) + (states("input_number.auto_lp_quartos_light_offset_off") | int) * 60) | timestamp_custom("%H:%M") }}'
      auto_lp_quartos_light_minutes_start_offset:
        friendly_name: 'Minutos de Acerto '
        icon_template: mdi:timer-sand
        value_template: '{{ states("input_number.auto_lp_quartos_light_offset_on") | int }}'
      auto_lp_quartos_light_minutes_stop_offset:
        friendly_name: 'Minutos de Acerto '
        icon_template: mdi:timer-sand
        value_template: '{{ states("input_number.auto_lp_quartos_light_offset_off") | int }}'
      auto_lp_quartos_light_start_seconds:
        value_template: '{{ ((as_timestamp(states.sun.sun.attributes.next_setting) + (states("input_number.auto_lp_quartos_light_offset_on") | int) * 60) | timestamp_custom("%H") | int * 3600 + (as_timestamp(states.sun.sun.attributes.next_setting) + (states("input_number.auto_lp_quartos_light_offset_on") | int) * 60) | timestamp_custom("%M") | int * 60)  }}'
      auto_lp_quartos_light_stop_seconds:
        value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_rising) + (states("input_number.auto_lp_quartos_light_offset_off") | int) * 60) | timestamp_custom("%H") | int * 3600 + (as_timestamp(states.sun.sun.attributes.next_rising) + (states("input_number.auto_lp_quartos_light_offset_off") | int) * 60) | timestamp_custom("%M") | int * 60 }}'
      auto_lp_quartos_light_start_offset:
        friendly_name: 'Tempo até ligar (h) '
        icon_template: mdi:timelapse
        value_template: '{{ (((states.sensor.auto_lp_quartos_light_start_seconds.state | int)) - ((as_timestamp (now()) | int ))) | timestamp_custom("%H:%M") }}'
      auto_lp_quartos_light_stop_offset:
        friendly_name: 'Tempo até desligar (h) '
        icon_template: mdi:timelapse
        value_template: '{{ (((states.sensor.auto_lp_quartos_light_stop_seconds.state | int)) - ((as_timestamp (now()) | int ))) | timestamp_custom("%H:%M") }}'

################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
## SWITCHES
################################################################################

#switch:

#### 


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### GROUPS
################################################################################

group:

#### GROUPO DE TODOS OS QUARTOS
  lp_quartos:
    name: Luzes de Presença dos Quartos
    control: hidden
    entities:
      - light.luz_de_presenca_q1_biachaty
      - light.luz_de_presenca_q2_rafa
      - light.luz_de_presenca_q3_pike_e_mike

#### SUB-GROUP QUARTO 1 - BIA E CHATY
  q1:
    name: Quarto 1 (Bia e Chaty)
    icon: mdi:hotel
    control: hidden
    entities:
      - light.luz_de_presenca_q1_biachaty

#### SUB-GROUP QUARTO 2 - RAFA
  q2:
    name: Quarto 2 (Rafa)
    icon: mdi:hotel
    control: hidden
    entities:
      - light.luz_de_presenca_q2_rafa

#### SUB-GROUP QUARTO 3 - PIKE E MIKE
  q3:
    name: Quarto 3 (Pike e Mike)
    icon: mdi:hotel
    control: hidden
    entities:
      - light.luz_de_presenca_q3_pike_e_mike
      - light.candeeiro_de_tecto_q3_pike_e_mike

################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
