################################################################################
# TYPE: Package
# FILENAME: package_kitchen_night_lights.yaml
# NAME: Kitchen Night Lights
################################################################################

#### 

################################################################################
#### SCRIPTS
################################################################################

script:

#### KITCHEN NIGHT LIGHTS - ON
  kitchen_night_lights_on:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'home/indoor/switch/H801-1AAF41/channel/4/set'
          payload_template: '255'
      - service: light.turn_on
        entity_id: group.lp_cozinha
      - service: script.notify_zanzito_jorge
        data:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes da Bancada e Mesa da Cozinha - LIGADAS'
      - service: script.notify_html5
        data_template:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes da Bancada e Mesa da Cozinha - LIGADAS'
          data:
            renotify: '1'
      - service: script.notify_save_to_file
        data:
          message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Luzes da Bancada e Mesa da Cozinha - LIGADAS'

#### KITCHEN NIGHT LIGHTS - NIGHT MODE ON
  kitchen_night_lights_night_mode_on:
    sequence:
      - service: light.turn_off
        entity_id: light.luz_de_presenca_cozinha_1_bancada
      - service: light.turn_on
        entity_id: light.luz_de_presenca_cozinha_2_mesa
        data:
          brightness: 20
      - service: script.notify_zanzito_jorge
        data:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes da Bancada e Mesa da Cozinha - INICIO DO MODO NOCTURNO'
      - service: script.notify_html5
        data_template:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes da Bancada e Mesa da Cozinha - INICIO DO MODO NOCTURNO'
          data:
            renotify: '1'
      - service: script.notify_save_to_file
        data:
          message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Luzes da Bancada e Mesa da Cozinha - INICIO DO MODO NOCTURNO'

####KITCHEN NIGHT LIGHTS - NIGHT MODE OFF
  kitchen_night_lights_night_mode_off:
    sequence:
      - service: light.turn_on
        entity_id: light.luz_de_presenca_cozinha_1_bancada
      - service: light.turn_on
        entity_id: light.luz_de_presenca_cozinha_2_mesa
        data:
          brightness: 255
      - service: script.notify_zanzito_jorge
        data:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes da Bancada e Mesa da Cozinha - FIM DO MODO NOCTURNO'
      - service: script.notify_html5
        data_template:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes da Bancada e Mesa da Cozinha - FIM DO MODO NOCTURNO'
          data:
            renotify: '1'
      - service: script.notify_save_to_file
        data:
          message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Luzes da Bancada e Mesa da Cozinha - FIM DO MODO NOCTURNO'

#### KITCHEN NIGHT LIGHTS - OFF
  kitchen_night_lights_off:
    sequence:
      - service: light.turn_off
        entity_id: group.lp_cozinha
      - service: script.notify_zanzito_jorge
        data:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes da Bancada e Mesa da Cozinha - DESLIGADAS'
      - service: script.notify_html5
        data_template:
          title: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }}'
          message: 'Luzes da Bancada e Mesa da Cozinha - DESLIGADAS'
          data:
            renotify: '1'
      - service: script.notify_save_to_file
        data:
          message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Luzes da Bancada e Mesa da Cozinha - DESLIGADAS'

#### LUZES DE PRESENÇA DA COZINHA - WEEKDAY
  auto_lp_cozinha_weekday_on:
    alias: Ligar
    sequence:
      - service: automation.trigger
        entity_id: automation.lp_cozinha_weekday__auto_on
  
  auto_lp_cozinha_weekday_night_mode_on:
    alias: Inicio Modo Nocturno
    sequence:
      - service: automation.trigger
        entity_id: automation.lp_cozinha_weekday__night_mode_auto_on
  
  auto_lp_cozinha_weekday_night_mode_off:
    alias: Fim Modo Nocturno
    sequence:
      - service: automation.trigger
        entity_id: automation.lp_cozinha_weekday__night_mode_auto_off
  
  auto_lp_cozinha_weekday_off:
    alias: Desligar
    sequence:
      - service: automation.trigger
        entity_id: automation.lp_cozinha_weekday__auto_off

#### LUZES DE PRESENÇA DA COZINHA - WEEKEND
  auto_lp_cozinha_weekend_on:
    alias: Ligar
    sequence:
      - service: automation.trigger
        entity_id: automation.lp_cozinha_weekend__auto_on
  
  auto_lp_cozinha_weekend_night_mode_on:
    alias: Inicio Modo Nocturno
    sequence:
      - service: automation.trigger
        entity_id: automation.lp_cozinha_weekend__night_mode_auto_on
  
  auto_lp_cozinha_weekend_night_mode_off:
    alias: Fim Modo Nocturno/Desligar
    sequence:
      - service: automation.trigger
        entity_id: automation.lp_cozinha_weekend__night_mode_auto_off

################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
#### AUTOMATIONS
################################################################################

automation:

#### LIGA LUZES DE PRESENÇA DA BANCADA E MESA DA COZINHA (SEG. E SEX.)
  - alias: 'LP Cozinha Weekday - Auto ON'
    initial_state: True
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: template
          value_template: '{{ states.sensor.auto_lp_cozinha_light_start_seconds.state | int <= ((((((as_timestamp (now())) | timestamp_custom("%H")) | int) * 3600) + ((((as_timestamp (now())) | timestamp_custom("%M")) | int) * 60) + (((as_timestamp (now())) | timestamp_custom("%S")) | int))) }}'
        - condition: state
          entity_id: group.familia
          state: 'home'
        - condition: state
          entity_id: input_boolean.modo_ferias
          state: 'off'
        - condition: state
          entity_id: 'group.lp_cozinha'
          state: 'off'
    action:
      - service: script.kitchen_night_lights_on

#### LIGA LUZES DE PRESENÇA DA BANCADA E MESA DA COZINHA (SAB. E DOM.)
  - alias: 'LP Cozinha Weekend - Auto ON'
    initial_state: True
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sat
            - sun
        - condition: template
          value_template: '{{ states.sensor.auto_lp_cozinha_light_start_seconds.state | int <= ((((((as_timestamp (now())) | timestamp_custom("%H")) | int) * 3600) + ((((as_timestamp (now())) | timestamp_custom("%M")) | int) * 60) + (((as_timestamp (now())) | timestamp_custom("%S")) | int))) }}'
        - condition: state
          entity_id: group.familia
          state: 'home'
        - condition: state
          entity_id: input_boolean.modo_ferias
          state: 'off'
        - condition: state
          entity_id: 'group.lp_cozinha'
          state: 'off'
    action:
      - service: script.kitchen_night_lights_on

#### INICIO DO MODO NOCTURNO - LUZES DE PRESENÇA DA MESA DA COZINHA (SEG. E SEX.)
  - alias: 'LP Cozinha Weekday - Night Mode Auto ON'
    initial_state: True
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: template
          value_template: '{{ (states.input_datetime.time_inicio_modo_nocturno_cozinha.attributes.timestamp | timestamp_custom("%H:%M",false)) <= ((as_timestamp (now())) | timestamp_custom("%H:%M")) <= (states.input_datetime.time_inicio_modo_nocturno_cozinha.attributes.timestamp | timestamp_custom("%H:%M",false)) }}'
        - condition: state
          entity_id: input_boolean.modo_ferias
          state: 'off'
    action:
      - service: script.kitchen_night_lights_night_mode_on

#### INICIO DO MODO NOCTURNO - LUZES DE PRESENÇA DA MESA DA COZINHA (SAB. E DOM.)
  - alias: 'LP Cozinha Weekend - Night Mode Auto ON'
    initial_state: True
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sat
            - sun
        - condition: template
          value_template: '{{ (states.input_datetime.time_inicio_modo_nocturno_cozinha.attributes.timestamp | timestamp_custom("%H:%M",false)) <= ((as_timestamp (now())) | timestamp_custom("%H:%M")) <= (states.input_datetime.time_inicio_modo_nocturno_cozinha.attributes.timestamp | timestamp_custom("%H:%M",false)) }}'
        - condition: state
          entity_id: input_boolean.modo_ferias
          state: 'off'
    action:
      - service: script.kitchen_night_lights_night_mode_on

#### FIM DO MODO NOCTURNO - LUZES DE PRESENÇA DA BANCADA DA COZINHA (SEG. E SEX.)
  - alias: 'LP Cozinha Weekday - Night Mode Auto OFF'
    initial_state: True
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: template
          value_template: '{{ (states.input_datetime.time_fim_modo_nocturno_cozinha.attributes.timestamp | timestamp_custom("%H:%M",false)) <= ((as_timestamp (now())) | timestamp_custom("%H:%M")) <= (states.input_datetime.time_fim_modo_nocturno_cozinha.attributes.timestamp | timestamp_custom("%H:%M",false)) }}'
        - condition: state
          entity_id: input_boolean.modo_ferias
          state: 'off'
    action:
      - service: script.kitchen_night_lights_night_mode_off

#### DESLIGA LUZES DE PRESENÇA DA MESA E BANCADA DA COZINHA (SEG. E SEX.)
  - alias: 'LP Cozinha Weekday - Auto OFF'
    initial_state: True
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: template
          value_template: '{{ (states.input_datetime.time_desliga_cozinha_semana.attributes.timestamp | timestamp_custom("%H:%M",false)) <= ((as_timestamp (now())) | timestamp_custom("%H:%M")) <= (states.input_datetime.time_desliga_cozinha_semana.attributes.timestamp | timestamp_custom("%H:%M",false)) }}'
    action:
      - service: script.kitchen_night_lights_off

#### FIM DO MODO NOCTURNO/DESLIGA - LUZES DE PRESENÇA DA MESA DA COZINHA (SAB. E DOM.)
  - alias: 'LP Cozinha Weekend - Night Mode Auto OFF'
    initial_state: True
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sat
            - sun
        - condition: template
          value_template: '{{ (states.input_datetime.time_desliga_cozinha_fds.attributes.timestamp | timestamp_custom("%H:%M",false)) <= ((as_timestamp (now())) | timestamp_custom("%H:%M")) <= (states.input_datetime.time_desliga_cozinha_fds.attributes.timestamp | timestamp_custom("%H:%M",false)) }}'
        - condition: state
          entity_id: input_boolean.modo_ferias
          state: 'off'
    action:
      - service: script.kitchen_night_lights_off

################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER
################################################################################

input_number:

#### Temporizador das luzes de presença da cozinha
  auto_lp_cozinha_light_offset_on:
    name: Minutos Acerto ( - | + )
    icon: mdi:timer
    min: -60
    max: 90
    step: 10
  
  auto_lp_cozinha_light_offset_off:
    name: Minutos Acerto ( - | + )
    icon: mdi:timer
    min: -90
    max: 90
    step: 10 

################################################################################
#### INPUT DATE TIME
################################################################################

input_datetime:

####  
  time_inicio_modo_nocturno_cozinha:
    name: 'Inicio Modo Nocturno'
    has_date: false
    has_time: true
    initial: '21:00'

####
  time_fim_modo_nocturno_cozinha:
    name: 'Fim Modo Nocturno'
    has_date: false
    has_time: true
    initial: '06:35'

#### 
  time_desliga_cozinha_semana:
    name: 'Luzes apagam (seg-sex) às'
    has_date: false
    has_time: true
    initial: '8:00'

####
  time_desliga_cozinha_fds:
    name: 'Luzes apagam (sab-dom) às'
    has_date: false
    has_time: true
    initial: '7:00' 

################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### 



################################################################################
#### SENSOR TEMPLATES
################################################################################

#### LUZES DE PRESENÇA DA COZINHA
  - platform: template
    sensors:
      auto_lp_cozinha_light_group_state:
        friendly_name: 'Estado actual '
        icon_template: mdi:apple-keyboard-option
        value_template: '{{ states.group.lp_cozinha.state }}'
      auto_lp_cozinha_light_start:
        friendly_name: 'Luzes acendem às '
        icon_template: mdi:lightbulb-on-outline
        value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) + (states("input_number.auto_lp_cozinha_light_offset_on") | int) * 60) | timestamp_custom("%H:%M") }}'
      auto_lp_cozinha_light_stop:
        friendly_name: 'Luzes apagam às '
        icon_template: mdi:lightbulb-outline
        value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_rising) + (states("input_number.auto_lp_cozinha_light_offset_off") | int) * 60) | timestamp_custom("%H:%M") }}'
      auto_lp_cozinha_light_minutes_start_offset:
        friendly_name: 'Minutos de Acerto '
        icon_template: mdi:timer-sand
        value_template: '{{ states("input_number.auto_lp_cozinha_light_offset_on") | int }}'
      auto_lp_cozinha_light_minutes_stop_offset:
        friendly_name: 'Minutos de Acerto '
        icon_template: mdi:timer-sand
        value_template: '{{ states("input_number.auto_lp_cozinha_light_offset_off") | int }}'
      auto_lp_cozinha_light_start_seconds:
        value_template: '{{ ((as_timestamp(states.sun.sun.attributes.next_setting) + (states("input_number.auto_lp_cozinha_light_offset_on") | int) * 60) | timestamp_custom("%H") | int * 3600 + (as_timestamp(states.sun.sun.attributes.next_setting) + (states("input_number.auto_lp_cozinha_light_offset_on") | int) * 60) | timestamp_custom("%M") | int * 60)  }}'
      auto_lp_cozinha_light_stop_seconds:
        value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_rising) + (states("input_number.auto_lp_cozinha_light_offset_off") | int) * 60) | timestamp_custom("%H") | int * 3600 + (as_timestamp(states.sun.sun.attributes.next_rising) + (states("input_number.auto_lp_cozinha_light_offset_off") | int) * 60) | timestamp_custom("%M") | int * 60 }}'
      auto_lp_cozinha_light_start_offset:
        friendly_name: 'Tempo até ligar (h) '
        icon_template: mdi:timelapse
        value_template: '{{ (((states.sensor.auto_lp_cozinha_light_start_seconds.state | int)) - ((as_timestamp (now()) | int ))) | timestamp_custom("%H:%M") }}'
      auto_lp_cozinha_light_stop_offset:
        friendly_name: 'Tempo até desligar (h) '
        icon_template: mdi:timelapse
        value_template: '{{ (((states.sensor.auto_lp_cozinha_light_stop_seconds.state | int)) - ((as_timestamp (now()) | int ))) | timestamp_custom("%H:%M") }}'
      cozinha_mesa_brightness:
        friendly_name: 'Brilho '
        value_template: '{{ states.light.luz_de_presenca_cozinha_2_mesa.attributes.brightness }}'

################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
## SWITCHES
################################################################################

#switch:

#### 


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### GROUPS
################################################################################

group:

#### COZINHA
  lp_cozinha:
    entities:
      - light.luz_de_presenca_cozinha_1_bancada
      - light.luz_de_presenca_cozinha_2_mesa 

################################################################################
#### CUSTOMIZE
################################################################################

homeassistant:

  customize:

#### 
    automation.luzes_de_presenca_da_cozinha_bancada__seg_a_sex__liga:
      friendly_name: 'Acender Auto B (seg-sex)'
      icon: mdi:brightness-auto
    automation.luzes_de_presenca_da_cozinha_bancada__seg_a_sex__desliga:
      friendly_name: 'Apagar Auto B (seg-sex)'
      icon: mdi:brightness-auto
    automation.luzes_de_presenca_da_cozinha_bancada_e_mesa__seg_a_sex__liga:
      friendly_name: 'Acender Auto B+M (seg-sex)'
      icon: mdi:brightness-auto
    automation.luzes_de_presenca_da_cozinha_bancada_e_mesa__seg_a_sex__desliga:
      friendly_name: 'Apagar Auto B+M (seg-sex)'
      icon: mdi:brightness-auto


####  ####  ####  ####
