################################################################################
# TYPE: Binary Sensors
# FILENAME: binary_sensors_wallpanel.yaml
# NAME: Wallpanel
################################################################################

#### ENTRADA
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/motion"
  name: "PIR - Entrada"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion


####  ####  ####  ####
