################################################################################
# TYPE: Binary Sensors
# FILENAME: binary_sensors_device_tracker.yaml
# NAME: New Device Tracker
################################################################################

## https://github.com/abmantis/homeassistant-custom-components

#### NEW DEVICE TRACKER
- platform: device_tracker_sensor
  entities:
## ZANZITO TRACKER
    - device_tracker.jmra
    - device_tracker.lslma
    - device_tracker.bama
## IMPRESSORAS
    - device_tracker.lexmark_x201n
## SERVIDORES E REDE
    - device_tracker.router_vodafone
    - device_tracker.ha_server
    - device_tracker.home_pbx
    - device_tracker.homecctv
    - device_tracker.cisco2950
    - device_tracker.smc_ap
## TELEMOVEIS
    - device_tracker.galaxy_s8
    - device_tracker.note4
    - device_tracker.lg_bello
    - device_tracker.motorola
## MULTIMEDIA
    - device_tracker.tvbox_sala
    - device_tracker.tv_sala
    - device_tracker.kodi_player_sala
    - device_tracker.nintendo_wii
## COMPUTADORES
    - device_tracker.neptune
    - device_tracker.phobos
    - device_tracker.venus
    - device_tracker.asus_k56c
## TABLETS
    - device_tracker.tablet_ja
    - device_tracker.tablet_bia
    - device_tracker.tablet_rafa
    - device_tracker.tablet_wallpanel_entrada
## TELEFONES IP
    - device_tracker.cisco7942
## CAMERAS
    - device_tracker.homecam01
    - device_tracker.homecam02
## EQUIPAMENTO DE AUTOMAÇÂO
    - device_tracker.esp_energy_monitor_01
    - device_tracker.esp_frontdoor
    - device_tracker.sonoffb45548
    - device_tracker.sonoff3c3169
    - device_tracker.sonoff3c1bdc
    - device_tracker.sonoffb43740
    - device_tracker.sonoffb440bd
    - device_tracker.sonoff4285ec
    - device_tracker.sonoff3b5864
    - device_tracker.sonoff3b9b97
    - device_tracker.sonoff3b963b
    - device_tracker.sonoff1aaf41
    - device_tracker.sonoff8cb88c
    - device_tracker.sonoffb43323
## DIVERSOS
    - device_tracker.esp32_30aea427d7f0
    - device_tracker.08fd0eff7ddc
    - device_tracker.0cbd511dd8cf
    - device_tracker.000ed1011fb5
    - device_tracker.0025cf441bd8
    - device_tracker.dcefcaba3675
    - device_tracker.b827ebb43e41
    - device_tracker.5ccf7f4c5874
    - device_tracker.5ccf7fb55ab7
    - device_tracker.5ccf7f53d01d
    - device_tracker.18fe341aaf41
    - device_tracker.78c3e9dd0da0


####  ####  ####  ####
