################################################################################
# TYPE: Package
# FILENAME: package_kitchen_night_lights.yaml
# NAME: Luzes de Presença da Cozinha
################################################################################

#### 

################################################################################
#### SCRIPTS
################################################################################

script:

#### KITCHEN NIGHT LIGHTS - ON
  manual_lp_cozinha_on:
    alias: Ligar
    sequence:
      - service: light.turn_on
        entity_id:
          - light.luz_de_presenca_cozinha_1_bancada
      - service: light.turn_on
        entity_id: light.luz_de_presenca_cozinha_2_mesa
        data:
          brightness: 255
#### KITCHEN NIGHT LIGHTS - OFF
  manual_lp_cozinha_off:
    alias: Desligar
    sequence:
      - service: light.turn_off
        entity_id:
          - light.luz_de_presenca_cozinha_1_bancada
          - light.luz_de_presenca_cozinha_2_mesa
#### KITCHEN NIGHT LIGHTS - NIGHT MODE
  manual_lp_cozinha_night_mode_on:
    alias: Modo Nocturno
    sequence:
      - service: light.turn_off
        entity_id:
          - light.luz_de_presenca_cozinha_1_bancada
      - service: light.turn_on
        entity_id: light.luz_de_presenca_cozinha_2_mesa
        data:
          brightness: 20


################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

input_boolean:

#### MANUAL MODE
  lp_cozinha_manual:
    name: Luzes em Manual
    icon: mdi:toggle-switch
#### MANUAL NIGHT MODE
  lp_cozinha_night_mode_manual:
    name: Modo Nocturno em Manual
    icon: mdi:toggle-switch 


################################################################################
#### INPUT NUMBER
################################################################################

input_number:

#### Temporizador das luzes de presença da cozinha
  auto_lp_cozinha_light_offset_on:
    name: Offset ON
    icon: mdi:timer
    unit_of_measurement: 'min.'
    min: -60
    max: 90
    step: 10

  night_mode_brightness:
    name: Brilho Modo Nocturno
    icon: mdi:timer
    unit_of_measurement: '%'
    min: 0
    max: 100
    step: 5


################################################################################
#### INPUT DATE TIME
################################################################################

input_datetime:

####  
  time_inicio_modo_nocturno_cozinha:
    name: 'Inicio Modo Nocturno'
    has_date: false
    has_time: true
    initial: '21:00'

####
  time_fim_modo_nocturno_cozinha:
    name: 'Fim Modo Nocturno'
    has_date: false
    has_time: true
    initial: '06:35'

#### 
  time_desliga_cozinha_semana:
    name: 'Luzes apagam (seg-sex) às'
    has_date: false
    has_time: true
    initial: '8:00'

####
  time_desliga_cozinha_fds:
    name: 'Luzes apagam (sab-dom) às'
    has_date: false
    has_time: true
    initial: '7:00' 

################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### LUZ DE PRESENÇA DA COZINHA 1 - BANCADA
  - platform: mqtt
    state_topic: "home/indoor/switch/SONOFF-BASIC-3C1BDC/ip"
    name: "IP Cozinha 1 - Bancada"
#### LUZ DE PRESENÇA DA COZINHA 2 - MESA
  - platform: mqtt
    state_topic: "home/indoor/switch/H801-1AAF41/ip"
    name: "IP Cozinha 2 - Mesa"
#### TPH Cozinha
  - platform: "mqtt"
    name: "Temperatura Cozinha"
    state_topic: "zigbee2mqtt/xiaomi_tph_cozinha"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    value_template: "{{ value_json.temperature }}" 
  - platform: "mqtt"
    name: "Humidade Cozinha"
    state_topic: "zigbee2mqtt/xiaomi_tph_cozinha"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: "Pressão Cozinha"
    state_topic: "zigbee2mqtt/xiaomi_tph_cozinha"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "Pa"
    icon: "mdi:speedometer"
    value_template: "{{ value_json.pressure }}"
  - platform: "mqtt"
    name: "Bateria THP Cozinha"
    state_topic: "zigbee2mqtt/xiaomi_tph_cozinha"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:battery-charging-wireless-50"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Voltagem THP Cozinha"
    state_topic: "zigbee2mqtt/xiaomi_tph_cozinha"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "V"
    icon: "mdi:battery-charging-wireless-50"
    value_template: "{{ value_json.voltage }}"
  - platform: "mqtt"
    name: "Link Quality THP Cozinha"
    state_topic: "zigbee2mqtt/xiaomi_tph_cozinha"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:battery-charging-wireless-50"
    value_template: "{{ value_json.linkquality }}"
####
  - platform: mqtt
    name: 'Brilho Modo Nocturno'
    state_topic: "tele/home/indoor/light/H801_4BDBA9/STATE"
    unit_of_measurement: '%'
    icon: mdi:brightness-7
    value_template: "{{ value_json.Dimmer }}"


################################################################################
#### SENSOR TEMPLATES
################################################################################

#### LUZES DE PRESENÇA DA COZINHA
  - platform: template
    sensors:
      auto_lp_cozinha_light_group_state:
        friendly_name: 'Estado actual '
        icon_template: mdi:apple-keyboard-option
        value_template: '{{ states.group.lp_cozinha.state }}'
      auto_lp_cozinha_light_start:
        friendly_name: 'Luzes acendem às '
        icon_template: mdi:lightbulb-on-outline
        value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_dusk) + (states("input_number.auto_lp_cozinha_light_offset_on") | int) * 60) | timestamp_custom("%H:%M") }}'
#      auto_lp_cozinha_light_stop:
#        friendly_name: 'Luzes apagam às '
#        icon_template: mdi:lightbulb-outline
#        value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_dawn) + (states("input_number.auto_lp_cozinha_light_offset_off") | int) * 60) | timestamp_custom("%H:%M") }}'
      auto_lp_cozinha_light_minutes_start_offset:
        friendly_name: 'Minutos de Acerto '
        icon_template: mdi:timer-sand
        value_template: '{{ states("input_number.auto_lp_cozinha_light_offset_on") | int }}'
#      auto_lp_cozinha_light_minutes_stop_offset:
#        friendly_name: 'Minutos de Acerto '
#        icon_template: mdi:timer-sand
#        value_template: '{{ states("input_number.auto_lp_cozinha_light_offset_off") | int }}'
      auto_lp_cozinha_light_start_seconds:
        value_template: '{{ ((as_timestamp(states.sun.sun.attributes.next_dusk) + (states("input_number.auto_lp_cozinha_light_offset_on") | int) * 60) | timestamp_custom("%H") | int * 3600 + (as_timestamp(states.sun.sun.attributes.next_dusk) + (states("input_number.auto_lp_cozinha_light_offset_on") | int) * 60) | timestamp_custom("%M") | int * 60)  }}'
#      auto_lp_cozinha_light_stop_seconds:
#        value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_dawn) + (states("input_number.auto_lp_cozinha_light_offset_off") | int) * 60) | timestamp_custom("%H") | int * 3600 + (as_timestamp(states.sun.sun.attributes.next_dawn) + (states("input_number.auto_lp_cozinha_light_offset_off") | int) * 60) | timestamp_custom("%M") | int * 60 }}'
      auto_lp_cozinha_light_start_offset:
        friendly_name: 'Tempo até ligar (h) '
        icon_template: mdi:timelapse
        value_template: '{{ (((states.sensor.auto_lp_cozinha_light_start_seconds.state | int)) - ((as_timestamp (now()) | int ))) | timestamp_custom("%H:%M") }}'
#      auto_lp_cozinha_light_stop_offset:
#        friendly_name: 'Tempo até desligar (h) '
#        icon_template: mdi:timelapse
#        value_template: '{{ (((states.sensor.auto_lp_cozinha_light_stop_seconds.state | int)) - ((as_timestamp (now()) | int ))) | timestamp_custom("%H:%M") }}'


################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
## SWITCHES
################################################################################

#switch:

#### 



################################################################################
## LIGHTS
################################################################################

light:

#### Switch Cozinha 1 - Bancada
  - platform: mqtt
    name: "Luz de Presença Cozinha 1 (Bancada)"
    state_topic: "home/indoor/switch/SONOFF-BASIC-3C1BDC/relay/0"
    command_topic: "home/indoor/switch/SONOFF-BASIC-3C1BDC/relay/0/set"
    availability_topic: "home/indoor/switch/SONOFF-BASIC-3C1BDC/status"
    qos: 1
    payload_on: 1
    payload_off: 0
    payload_available: 1
    payload_not_available: 0
    optimistic: false
    retain: true

#### Luz Cozinha 2 - Mesa
#  - platform: mqtt
#    name: "Luz de Presença Cozinha 2 (Mesa)"
#    state_topic: "home/indoor/switch/H801-1AAF41/relay/0"
#    command_topic: "home/indoor/switch/H801-1AAF41/relay/0/set"
#    brightness_state_topic: "home/indoor/switch/H801-1AAF41/channel/4"
#    brightness_command_topic: "home/indoor/switch/H801-1AAF41/channel/4/set"
#    qos: 1
#    payload_on: 1
#    payload_off: 0
#    retain: true

#### 
  - platform: mqtt
    name: "Luz de Presença Cozinha 2 (Mesa)"
    state_topic: "stat/home/indoor/light/H801_4BDBA9/POWER"
    command_topic: "cmnd/home/indoor/light/H801_4BDBA9/POWER"
    availability_topic: "tele/home/indoor/light/H801_4BDBA9/LWT"
    rgb_state_topic: "stat/home/indoor/light/H801_4BDBA9/COLOR"
    rgb_command_topic: "cmnd/home/indoor/light/H801_4BDBA9/COLOR"
    rgb_command_template: "{{ '%02x%02x%02x0000' | format(red, green, blue) }}"
    brightness_state_topic: "tele/home/indoor/light/H801_4BDBA9/STATE"
    brightness_value_template: "{{ value_json.Dimmer }}"
    brightness_command_topic: "cmnd/home/indoor/light/H801_4BDBA9/Dimmer"
    brightness_scale: 100
    color_temp_command_topic: "cmnd/home/indoor/light/H801_4BDBA9/CT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

####


####  ####  ####  ####
