################################################################################
# TYPE: Package
# FILENAME: package_sistema_last_notifications.yaml
# NAME: Last Notifications
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER (OLD INPUT_SLIDER)
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### 10
  - platform: command_line
    name: "notificação 10"
    command: "tail -n 10 /config/notifications.txt | sed '2,10d' $1"
#### 09
  - platform: command_line
    name: "notificação 09"
    command: "tail -n 9 /config/notifications.txt | sed '2,9d' $1"
#### 08
  - platform: command_line
    name: "notificação 08"
    command: "tail -n 8 /config/notifications.txt | sed '2,8d' $1"
#### 07
  - platform: command_line
    name: "notificação 07"
    command: "tail -n 07 /config/notifications.txt | sed '2,7d' $1"
#### 06
  - platform: command_line
    name: "notificação 06"
    command: "tail -n 6 /config/notifications.txt | sed '2,6d' $1"
#### 05
  - platform: command_line
    name: "notificação 05"
    command: "tail -n 5 /config/notifications.txt | sed '2,5d' $1"
#### 04
  - platform: command_line
    name: "notificação 04"
    command: "tail -n 4 /config/notifications.txt | sed '2,4d' $1"
#### 03
  - platform: command_line
    name: "notificação 03"
    command: "tail -n 3 /config/notifications.txt | sed '2,3d' $1"
#### 02
  - platform: command_line
    name: "notificação 02"
    command: "tail -n 2 /config/notifications.txt | sed '2,2d' $1"
#### 01
  - platform: command_line
    name: "notificação 01"
    command: "tail -n 1 /config/notifications.txt | sed '2,1d' $1"



################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
#### BINARY SENSOR TEMPLATES
################################################################################

####



################################################################################
## SWITCHES
################################################################################

#switch:

#### 



################################################################################
## LIGHTS
################################################################################

#light:

#### 



################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 


####  ####  ####  ####

