################################################################################
# TYPE: Package
# FILENAME: package_q2.yaml
# NAME: Quarto 2
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER (OLD INPUT_SLIDER)
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### SONOFF-TH10-3B5864 (LUZ DE PRESENÇA DO Q2)
  - platform: mqtt
    state_topic: "home/indoor/switch/SONOFF-TH10-3B5864/temperature"
    name: "Temperatura Q2"
    unit_of_measurement: °C
    retain: true
    force_update: true
  - platform: mqtt
    state_topic: "home/indoor/switch/SONOFF-TH10-3B5864/humidity"
    name: "Humidade Q2"
    unit_of_measurement: '%'
    retain: true
    force_update: true 


################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
#### BINARY SENSOR TEMPLATES
################################################################################

####



################################################################################
## SWITCHES
################################################################################

#switch:

#### 



################################################################################
## LIGHTS
################################################################################

light:

#### LP Q2
- platform: mqtt
  name: "Luz de Presença Q2"
  state_topic: "home/indoor/switch/SONOFF-TH10-3B5864/relay/0"
  command_topic: "home/indoor/switch/SONOFF-TH10-3B5864/relay/0/set"
  qos: 1
  payload_on: 1
  payload_off: 0
  optimistic: false
  retain: true


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
