################################################################################
# TYPE: Package
# FILENAME: package_device_trackers.yaml
# NAME: Localização da Familia
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

script:

#### JMRA Home
  set_jmra_home:
    alias: Força em Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/jmra/location'
          retain: true
          payload: !secret payload_home

#### JMRA Not Home
  set_jmra_not_home:
    alias: Força Fora de Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/jmra/location'
          retain: true
          payload: '{"latitude": 0.0,"longitude": 0.0}'

#### JMRA ETAR Chelas
  set_jmra_etar_chelas:
    alias: Força ETAR Chelas
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/jmra/location'
          retain: true
          payload: !secret payload_etar_chelas

#### JMRA EMEL
  set_jmra_emel:
    alias: Força EMEL
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/jmra/location'
          retain: true
          payload: !secret payload_emel

#### JMRA Escola Bia
  set_jmra_escola_bia:
    alias: Força Escola Bia
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/jmra/location'
          retain: true
          payload: !secret payload_escola_bia

#### JMRA NOT HOME
  set_jmra_escola_not_home:
    alias: Força Not Home
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.jorge_status_dropdown
          option: not_home

#### LSLMA Home
  set_lslma_home:
    alias: Força em Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/lslma/location'
          retain: true
          payload: !secret payload_home

#### LSLMA Not Home
  set_lslma_not_home:
    alias: Força Fora de Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/lslma/location'
          retain: true
          payload: '{"latitude": 0.0,"longitude": 0.0}'

#### BAMA Home
  set_bama_home:
    alias: Força em Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/bama/location'
          retain: true
          payload: !secret payload_home

#### BAMA Not Home
  set_bama_not_home:
    alias: Força Fora de Casa
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/bama/location'
          retain: true
          payload: '{"latitude": 0.0,"longitude": 0.0}'


################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### BATERIA

## PIKE
  - platform: mqtt
    state_topic: "zanzito/jmra/battery_level"
    name: "Pike - Bateria"
    unit_of_measurement: '%'
    retain: true

## MIKE
  - platform: mqtt
    state_topic: "zanzito/lslma/battery_level"
    name: "Mike - Bateria"
    unit_of_measurement: '%'
    retain: true

## BIA
  - platform: mqtt
    state_topic: "zanzito/bama/battery_level"
    name: "Bia - Bateria"
    unit_of_measurement: '%'
    retain: true 

#### LOCALIZAÇÃO

## JORGE
  - platform: mqtt
    state_topic: "zanzito/jmra/location"
    name: "jmra gps"
    retain: true

## LARA
  - platform: mqtt
    state_topic: "zanzito/lslma/location"
    name: "lslma gps"
    retain: true

## BIA
  - platform: mqtt
    state_topic: "zanzito/bama/location"
    name: "bama gps"
    retain: true


################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
## SWITCHES
################################################################################

#switch:

#### 


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
