################################################################################
# TYPE: Package
# FILENAME: package_q1.yaml
# NAME: Quarto 1
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER (OLD INPUT_SLIDER)
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### LUZ DE PRESENÇA Q1
  - platform: mqtt
    state_topic: "home/indoor/switch/SONOFF-TH16-3C3169/temperature"
    name: "Temperatura Q1"
    unit_of_measurement: °C
    retain: true
    force_update: true
  - platform: mqtt
    state_topic: "home/indoor/switch/SONOFF-TH16-3C3169/humidity"
    name: "Humidade Q1"
    unit_of_measurement: '%'
    retain: true
    force_update: true


################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
#### BINARY SENSOR TEMPLATES
################################################################################

####



################################################################################
## SWITCHES
################################################################################

#switch:

#### 



################################################################################
## LIGHTS
################################################################################

light:

#### LP Q1
  - platform: mqtt
    name: "Luz de Presença Q1"
    state_topic: "home/indoor/switch/SONOFF-TH16-3C3169/relay/0"
    command_topic: "home/indoor/switch/SONOFF-TH16-3C3169/relay/0/set"
    qos: 1
    payload_on: 1
    payload_off: 0
    optimistic: false
    retain: true


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
