################################################################################
# TYPE: Package
# FILENAME: package_q3.yaml
# NAME: ??
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER (OLD INPUT_SLIDER)
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### LUZ DE PRESENÇA DO Q3
- platform: mqtt
  state_topic: "home/indoor/switch/SONOFF-TH10-3B9B97/temperature"
  name: "Temperatura Q3"
  unit_of_measurement: °C
  retain: true
  force_update: true
- platform: mqtt
  state_topic: "home/indoor/switch/SONOFF-TH10-3B9B97/humidity"
  name: "Humidade Q3"
  unit_of_measurement: '%'
  retain: true
  force_update: true


################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
#### BINARY SENSOR TEMPLATES
################################################################################

####



################################################################################
## SWITCHES
################################################################################

#switch:

#### 



################################################################################
## LIGHTS
################################################################################

light:

#### LP Q3
- platform: mqtt
  name: "Luz de Presença Q3"
  state_topic: "home/indoor/switch/SONOFF-TH10-3B9B97/relay/0"
  command_topic: "home/indoor/switch/SONOFF-TH10-3B9B97/relay/0/set"
  qos: 1
  payload_on: 1
  payload_off: 0
  optimistic: false
  retain: true

#### LIGHT Q3
- platform: mqtt
  name: "Candeeiro de Tecto Q3"
  state_topic: "home/indoor/switch/SONOFF-TOUCH-1CH-8CB88C/relay/0"
  command_topic: "home/indoor/switch/SONOFF-TOUCH-1CH-8CB88C/relay/0/set"
  qos: 1
  payload_on: 1
  payload_off: 0
  optimistic: false
  retain: true


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
