################################################################################
# TYPE: Package
# FILENAME: package_natal.yaml
# NAME: ??
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
#### AUTOMATIONS
################################################################################

#automation:

#### ACENDE A ARVORE DE NATAL
#  - alias: 'Acende Árvore de Natal'
#    initial_state: 'on'
#    trigger:
#      - platform: time_pattern
#        minutes: '/1'
#        seconds: 01
#    condition:
#      condition: and
#      conditions:
#        - condition: template
#          value_template: '{{ (states.input_datetime.time_liga_arvore_natal.attributes.timestamp | timestamp_custom("%H:%M",False)) <= ((as_timestamp (now(""))) | timestamp_custom("%H:%M",False))  <= (states.input_datetime.time_liga_arvore_natal.attributes.timestamp | timestamp_custom("%H:%M",False)) }}'
#        - condition: state
#          entity_id: group.familia
#          state: 'home'
#        - condition: state
#          entity_id: input_boolean.modo_ferias
#          state: 'off'
#    action:
#      - service: switch.turn_on
#        data_template:
#          entity_id: switch.arvore_de_natal
#      - service: script.notify_save_to_file
#        data:
#          message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Árvore de Natal - LIGADA'
  
#### APAGA A ARVORE DE NATAL
#  - alias: 'Apaga Árvore de Natal'
#    initial_state: 'on'
#    trigger:
#      - platform: time_pattern
#        minutes: '/1'
#        seconds: 01
#    condition:
#      condition: and
#      conditions:
#        - condition: template
#          value_template: '{{ (states.input_datetime.time_desliga_arvore_natal.attributes.timestamp | timestamp_custom("%H:%M",False)) <= ((as_timestamp (now(""))) | timestamp_custom("%H:%M",False)) <= (states.input_datetime.time_desliga_arvore_natal.attributes.timestamp | timestamp_custom("%H:%M",False)) }}'
#        - condition: state
#          entity_id: group.familia
#          state: 'home'
#    action:
#      - service: switch.turn_off
#        entity_id: switch.arvore_de_natal
#      - service: script.notify_save_to_file
#        data:
#          message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Árvore de Natal - DESLIGADA'


################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER (OLD INPUT_SLIDER)
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

####
#  time_liga_arvore_natal:
#    name: 'Acende às'
#    has_date: false
#    has_time: true
#    initial: '18:00'

####
#  time_desliga_arvore_natal:
#    name: 'Apaga às'
#    has_date: false
#    has_time: true
#    initial: '23:00'


################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### LUZ DE FUNDO TV
  - platform: mqtt
    state_topic: "home/indoor/switch/SONOFF-BASIC-B440BD/ip"
    name: "IP Luz de Fundo TV"
#### CANDEEIRO DE PÉ
  - platform: mqtt
    state_topic: "home/indoor/switch/SONOFF-BASIC-B43323/ip"
    name: "IP Candeeiro de Pé"
#### THP SALA
  - platform: "mqtt"
    name: "Temperatura Sala"
    state_topic: "zigbee2mqtt/xiaomi_tph_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    value_template: "{{ value_json.temperature }}"
  - platform: "mqtt"
    name: "Humidade Sala"
    state_topic: "zigbee2mqtt/xiaomi_tph_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: "Pressão Sala"
    state_topic: "zigbee2mqtt/xiaomi_tph_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "Pa"
    icon: "mdi:speedometer"
    value_template: "{{ value_json.pressure }}"
  - platform: "mqtt"
    name: "Bateria THP Sala"
    state_topic: "zigbee2mqtt/xiaomi_tph_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:battery-charging-wireless-50"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Voltagem THP Sala"
    state_topic: "zigbee2mqtt/xiaomi_tph_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "V"
    icon: "mdi:battery-charging-wireless-50"
    value_template: "{{ value_json.voltage }}"
  - platform: "mqtt"
    name: "Link Quality THP Sala"
    state_topic: "zigbee2mqtt/xiaomi_tph_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:battery-charging-wireless-50"
    value_template: "{{ value_json.linkquality }}" 


################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
## SWITCHES
################################################################################

#switch:

#### 
#  - platform: mqtt
#    name: "Árvore de Natal"
#    state_topic: "zigbee2mqtt/ikea_switch_01"
#    availability_topic: "zigbee2mqtt/bridge/state"
#    payload_off: "OFF"
#    payload_on: "ON"
#    value_template: "{{ value_json.state }}"
#    command_topic: "zigbee2mqtt/ikea_switch_01/set"


################################################################################
## LIGHTS
################################################################################

light:

#### LUZ DE FUNDO TV
- platform: mqtt
  name: "Luz de Fundo (TV)"
  state_topic: "home/indoor/switch/SONOFF-BASIC-4285EC/relay/0"
  command_topic: "home/indoor/switch/SONOFF-BASIC-4285EC/relay/0/set"
  availability_topic: "home/indoor/switch/SONOFF-BASIC-4285EC/status"
  qos: 1
  payload_on: 1
  payload_off: 0
  payload_available: 1
  payload_not_available: 0
  optimistic: false
  retain: true

#### CANDEEIRO DE PÉ
- platform: mqtt
  name: "Candeeiro de Pé"
  state_topic: "home/indoor/switch/SONOFF-BASIC-B43323/relay/0"
  command_topic: "home/indoor/switch/SONOFF-BASIC-B43323/relay/0/set"
  availability_topic: "home/indoor/switch/SONOFF-BASIC-B43323/status"
  qos: 1
  payload_on: 1
  payload_off: 0
  payload_available: 1
  payload_not_available: 0
  optimistic: false
  retain: true


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
