################################################################################
# TYPE: Package
# FILENAME: package_.yaml
# NAME: ??
################################################################################

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 



################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 



################################################################################
#### AUTOMATIONS
################################################################################

#automation:

#### 



################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 



################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 



################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 



################################################################################
#### INPUT NUMBER (OLD INPUT_SLIDER)
################################################################################

#input_number:

#### 


################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 



################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 



################################################################################
#### SENSORS
################################################################################

sensor:

#### 
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/xiaomi_cube_01"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:gesture-double-tap"
    value_template: "{{ value_json.action }}"
    json_attributes: 
      - "angle"
      - "side"
      - "from_side"
      - "to_side"
      - "brightness"
      - "angle_x_absolute"
      - "angle_y_absolute"
      - "angle_z"
      - "angle_y"
      - "angle_x"
      - "unknown_data"
    force_update: true

#### CUBO 01 - BATERIA
  - platform: "mqtt"
    name: "Bateria Cubo 01"
    state_topic: "zigbee2mqtt/xiaomi_cube_01"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:battery-charging-wireless-50"
    value_template: "{{ value_json.battery }}"

#### CUBO 01 - VOLTAGEM
  - platform: "mqtt"
    name: "Voltagem Cubo 01"
    state_topic: "zigbee2mqtt/xiaomi_cube_01"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "V"
    icon: "mdi:battery-charging-wireless-50"
    value_template: "{{ value_json.voltage }}"

#### CUBO 01 - LINK QUALITY
  - platform: "mqtt"
    name: "Link Quality Cubo 01"
    state_topic: "zigbee2mqtt/xiaomi_cube_01"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    icon: "mdi:battery-charging-wireless-50"
    value_template: "{{ value_json.linkquality }}"


################################################################################
#### SENSOR TEMPLATES
################################################################################

####



################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 



################################################################################
## SWITCHES
################################################################################

#switch:

#### 


################################################################################
## ALERTS
################################################################################

#alert:

#### 



################################################################################
#### CUSTOMIZE
################################################################################

#homeassistant:

#  customize:

#### 



####  ####  ####  ####
